name: workspace_deployment

on:
    push:
        branches: [workspace_publish]

    workflow_dispatch:

jobs:
    release:
        # You also can use the self-hosted runners.
        name: published code 
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - name: checkout code
          uses: actions/checkout@v2
        
        - name: Synapse workspace deployment
          uses: azure/synapse-workspace-deployment@release-1.0
          
          with:
                      
           TargetWorkspaceName: 'synapseworkspace-prod-2207'
           TemplateFile: './synapseworkspace-dev-2207/TemplateForWorkspace.json'
           ParametersFile: './synapseworkspace-dev-2207/TemplateParametersForWorkspace.json'
         # OverrideArmParameters: './path of the parameters.yaml'
           environment: 'Azure Public'
           resourceGroup: 'RG-Dev-2207'
           clientId: ${{secrets.CLIENTID}}
           clientSecret:  ${{secrets.CLIENTSECRET}}
           subscriptionId: ${{secrets.SUBCRIPTIONID}}
           tenantId: ${{secrets.TENANTID}}
           DeleteArtifactsNotInTemplate: 'true'
           managedIdentity: 'False'
